name: ySpawners
authors: [yChusy]
version: 1.2.9-STABLE
main: com.ystoreplugins.yspawners.Main
depend: [Vault]
softdepend: [PlaceholderAPI, PlotSquared, AtlasEconomy]
commands:
   spawners:
      aliases: [spawner, gerador, geradores]